VIEW_MULTI_SET = 'multiset'
VIEW_SET = 'set'
VIEW_SEQUENCE = 'sequence'

VIEWS = {VIEW_MULTI_SET, VIEW_SET, VIEW_SEQUENCE}

DIRECTION_FORWARD = 'forward'
DIRECTION_BACKWARD = 'backward'
DIRECTIONS = {DIRECTION_FORWARD, DIRECTION_BACKWARD}

DECORATION_ARC_FREQUENCY = 'arc_frequency'
DECORATIONS = {DECORATION_ARC_FREQUENCY}

PARAM_KEY_VIEW = 'view'
PARAM_KEY_WINDOW = 'window'
PARAM_KEY_DIRECTION = 'direction'
PARAM_KEY_DECORATION = 'decoration'
DEFAULT_PARAMETERS = {PARAM_KEY_VIEW: VIEW_SEQUENCE, PARAM_KEY_WINDOW: 2, PARAM_KEY_DIRECTION: DIRECTION_FORWARD, PARAM_KEY_DECORATION: DECORATIONS}